### ISSUE TITLE
build on MAC OSX

### ISSUE THREAD

**Issue by phrocker** [phrocker/sharkbite#2]

**Comment by mjwall** [comment]
Got dependencies installed with homebrew.  Will document.  Tried using clang, but compile failed with ld symbols error on vtable.  Will brew install gcc and try again

**Comment by phrocker** [comment]
I tried on my mac at home and had a bad time. i used homebrew as well, but saw the vtable symbol errors, which are easily resolved, but will take a few days. I can commit the ones that I've fixed thus far as an example.

**Comment by phrocker** [comment]
I only tried clang, though...

**Comment by phrocker** [comment]
Believed to be solved.
