### ISSUE TITLE
[Python] Opening zookeeper connection 2nd time causes munmap_chunk(): invalid pointer error

### ISSUE THREAD

**Issue by loomlike** [phrocker/sharkbite#41]
Creating ZookeeperInstance once and call scanning multiple time works as expected.

But if I create ZookeeperInstance again and call scanning, it throws an error `munmap_chunk(): invalid pointer:`

This (creating ZookeeperInstance multiple times) maybe not the expected pattern, but could happen often when working on Jupyter notebook.

Do I have to close the connection before creating a new one?
FYI, `scanner.close()` doesn't resolve the issue.

**Comment by phrocker** [comment]
@loomlike Thanks for reporting this. The Issue is that some object lifetimes rely on the zookeeper instance and python is getting rid of them prematurely -- hence the invalid pointer. There is a solution to this so I will add some integration tests to the the python suite to test this. 

I want to be clear that i"m solving your case though. Are you creating a new zookeeper instance and then all new table operations objects?

**Comment by loomlike** [comment]
@phrocker thank you for the clarification. Recreating all the objects seems resolved the issue. Now I have a class that keeps all zk related objects and creating the class object multiple times work without any issues.

**Comment by phrocker** [comment]
@loomlike I have a fix to make that less of a problem -- in no way do I want developers worrying about object lifetimes, so my regression test allows you to create a new ZK instance and older table operations and scanners should still function as you would expect. Added some regression tests will push up into a PR this weekend most likely.

**Comment by phrocker** [comment]
@loomlike Can you re-try? I've been running in various environments without issue . Let me know if I can be of assistance.

**Comment by loomlike** [comment]
I've moved to another project and the Accumulo cluster I'd tested is teared down already... so it is difficult for me to retry now... but thank you for your assist. The custom pytorch dataset class I implemented worked well.

You can close this issue as you confirmed this is resolved.
