### ISSUE TITLE
Create python example. 

### ISSUE THREAD

**Issue by phrocker** [phrocker/sharkbite#9]

**Comment by mjwall** [comment]
Maybe this should be broken out into 3 tickets.  I'd also like to see a nodejs example.

Anyway, some links on approaches to building a ruby gem with native bindings

https://www.amberbit.com/blog/2014/6/12/calling-c-cpp-from-ruby/
http://engineering.gusto.com/simple-ruby-c-extensions-with-swig/
http://patshaughnessy.net/2011/10/31/dont-be-terrified-of-building-native-extensions
http://blog.zachallett.com/howto-ruby-c-extension-with-a-static-library/
http://stackoverflow.com/questions/9251554/c-ruby-extension-with-external-libraries

**Comment by phrocker** [comment]
I have moved toward pybind11  because of the value it provides with object lifetime management. 

https://github.com/phrocker/sharkbite/blob/master/examples/pythonexample.py
