### ISSUE TITLE
Explore porting to Rust

### ISSUE THREAD

**Issue by phrocker** [phrocker/sharkbite#90]
This can be done in a stepwise approach. We should figure out what can/should be moved.

Rust and C++ should be interoperable, so we should be able to move the user facing API first, and slowly port the infrastructure code. 

@mjwall  what do you think?

**Comment by mjwall** [comment]
Sounds interesting.  Do you have a specific goal or goals in mind switching to Rust?  How well does adding Python and other bindings work with Rust?

**Comment by phrocker** [comment]
@mjwall  sorry I missed your response. I think my primary goal is to learn and support Rust. I think in retrospect I would probably not do a total re-write and simply wrap it.

**Comment by phrocker** [comment]
I don't think this is a pressing need. Closing for now.
